name: Cron Actions
on: 
  schedule:
  - cron: '* * * * *'

jobs:
  cronJob:
    name: Cron job
    runs-on: ubuntu-latest

    steps:
    - name: Echo text
      run: |
         echo "This is a cron job"
