name: Hola
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        shell: bash
        run: |
          ls -a
      